#! /bin/bash 

RANDOM_SEED=2024

command_generator() 
{
    echo python3.6 data_maker.py -NUM_NODES $1 -NUM_EDGES $2 -RANDOM_SEED $3
}

filename_generator()
{
    echo "graph_$1_$2_$3"
}

for i in {100..999}
do
    num_nodes=$i
    num_edges=$(( $num_nodes * 5 ))
    $(command_generator ${num_nodes} ${num_edges} ${RANDOM_SEED}) > $(filename_generator ${num_nodes} ${num_edges} ${RANDOM_SEED})
done

